"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%&au^!_fm9ds3r=g#xpj+kqz&+8fawjmh*i*k&s9l%dn%fbn3b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
]
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# 4. HTTPS-Only Cookies (Crucial for production)
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
# Use HttpOnly flag to prevent client-side JavaScript access to session cookie
SESSION_COOKIE_HTTPONLY = True 
CSRF_COOKIE_HTTPONLY = True

# 5. XSS/Clickjacking Prevention Headers
X_FRAME_OPTIONS = 'DENY' # Prevents Clickjacking by blocking embedding in an iframe
SECURE_BROWSER_XSS_FILTER = True # Recommended, though modern browsers use XSS auditors
SECURE_CONTENT_TYPE_NOSNIFF = True # Prevents browsers from guessing the content type (MIME sniffing)

# 6. HSTS (HTTP Strict Transport Security) - Enforces HTTPS after first visit
# SECURE_HSTS_SECONDS = 31536000 # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CspMiddleware'
]

CSP_DEFAULT_SRC = ("'self'",) # Default policy is 'self' (only content from your domain)
CSP_SCRIPT_SRC = ("'self'", "https://trustedcdn.com") # Only allow scripts from your domain and trusted CDNs
CSP_STYLE_SRC = ("'self'", "https://trustedcdn.com") # Only allow styles from your domain and trusted CDNs
CSP_IMG_SRC = ("'self'", "data:") # Allows images from your domain and inline base64 images
CSP_FRAME_ANCESTORS = ("'self'",) # Stronger defense than X_FRAME_OPTIONS for frames

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Where to redirect after successful login
LOGIN_REDIRECT_URL = '/relationship/books/' 
# Where to redirect if a user tries to access a protected page without logging in
LOGIN_URL = '/relationship/login/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
